### ISSUE TITLE
"darkmode" param doesn't do anything

### ISSUE THREAD

**Issue by Vectorrent** [HelloRusk/HugoTeX#13]
When I set this param in config.toml:
```
[Params]
  darkmode = true
```
Nothing happens. Dark mode is not applied to the theme. 

I am using Hugo v0.100.2. 

Of course, I can overwrite the CSS myself, but it would be nice if this param worked.

**Comment by kaisugi** [comment]
I tried myself in #14 and found the param still worked for me (Hugo v0.100.2)

https://hugotex-git-hugo-v01002-7xrusk.vercel.app/

![スクリーンショット 2022-10-21 12 07 38](https://user-images.githubusercontent.com/36184621/197102405-c8d03519-f7ca-4950-8fbe-59a74c80ce01.png)

**Comment by Vectorrent** [comment]
How strange! Your site is white in my browser. 

![image](https://user-images.githubusercontent.com/94832312/197103053-5c57d2ec-e92e-402c-985d-e47c442f9929.png)

This is happening in both Firefox and Chrome.

**Comment by kaisugi** [comment]
I guess the current style file sets dark-mode only if your OS settings follow dark-mode
![スクリーンショット 2022-10-21 12 21 04](https://user-images.githubusercontent.com/36184621/197104523-6753f01e-645e-4d12-a108-2b766ae3e9f6.png)

Maybe I should change this behavior so that you can use dark-mode on your website even if you don't wanna use dark-mode on your OS...

**Comment by Vectorrent** [comment]
Ah, yeah, this Firefox setting fixes the problem:
![image](https://user-images.githubusercontent.com/94832312/197104952-e121bc8e-1601-4575-b41c-9a60dedcc614.png)
Nevertheless, now that I know what was causing it - I think this is a really cool feature! Thanks for the help!
